# Generated by Django 5.2.6 on 2025-12-15 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('files_evaluation_enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CurricularArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MandatoryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='mandatory_documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('paternal_surname', models.CharField(max_length=30)),
                ('maternal_surname', models.CharField(max_length=30)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrelationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('curricular_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prelations', to='api.curriculararea')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prelations', to='api.level')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prelations', to='api.modality')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prelations', to='api.prelationorder')),
            ],
            options={
                'unique_together': {('modality', 'level', 'curricular_area', 'order')},
            },
        ),
        migrations.CreateModel(
            name='PrelationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='prelation_documents/')),
                ('prelation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.prelation')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dependency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institutions', to='api.dependency')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institutions', to='api.institutiontype')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institutions', to='api.level')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institutions', to='api.modality')),
                ('service_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institutions', to='api.servicemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=190)),
                ('type', models.CharField(choices=[('RequirementsVerification', 'Verificación de Requisitos'), ('PreliminaryEvaluation', 'Evaluación Preliminar'), ('PreliminaryResults', 'Publicación de Resultados'), ('ClaimsPeriod', 'Periodo de Reclamos'), ('CorrectsClaims', 'Corrección de Reclamos'), ('FinalResults', 'Publicación de Resultados Finales'), ('Adjudication', 'Adjudicación')], max_length=30)),
                ('order', models.PositiveIntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_qualifiable', models.BooleanField(default=False)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='api.contractingprocess')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nexus_code', models.CharField(max_length=50, unique=True)),
                ('position', models.CharField(max_length=100)),
                ('workday', models.CharField(max_length=100)),
                ('curricular_area', models.CharField(max_length=100)),
                ('vacancy_type', models.CharField(max_length=100)),
                ('vacancy_reason', models.CharField(max_length=100)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='api.institution')),
            ],
        ),
        migrations.CreateModel(
            name='ConvocatoriaAdjudicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_convocatoria', models.PositiveIntegerField(help_text='1, 2, 3...')),
                ('nombre', models.CharField(help_text='Ej: Primera Convocatoria - Plazas Rurales', max_length=100)),
                ('fecha_hora', models.DateTimeField()),
                ('lugar_o_enlace', models.CharField(max_length=255)),
                ('finalizada', models.BooleanField(default=False)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocatorias', to='api.stage')),
            ],
            options={
                'ordering': ['numero_convocatoria'],
                'unique_together': {('stage', 'numero_convocatoria')},
            },
        ),
        migrations.CreateModel(
            name='Subgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='api.group')),
            ],
            options={
                'unique_together': {('group', 'name')},
            },
        ),
    ]
