# Generated by Django 5.2.6 on 2025-12-16 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_modality_abbreviature_persondocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modality',
            name='description',
        ),
    ]
