# Generated by Django 5.2.6 on 2025-12-16 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_modality_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='description',
        ),
    ]
