# Generated by Django 5.2.6 on 2025-12-16 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_curriculararea_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prelation',
            name='curricular_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prelations', to='api.curriculararea'),
        ),
    ]
