# Generated by Django 5.2.6 on 2025-12-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_prelation_curricular_area'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prelation',
            unique_together={('modality', 'curricular_area', 'order')},
        ),
        migrations.RemoveField(
            model_name='prelation',
            name='level',
        ),
        migrations.AddField(
            model_name='prelation',
            name='level',
            field=models.ManyToManyField(related_name='prelations', to='api.level'),
        ),
    ]
