# Generated by Django 5.2.6 on 2025-12-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_prelation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prelation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
