# Generated by Django 5.2.6 on 2025-12-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_prelation_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modality',
            name='abbreviature',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
