# Generated by Django 5.2.6 on 2025-12-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_modality_abbreviature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modality',
            name='abbreviature',
            field=models.CharField(max_length=45, null=True, unique=True),
        ),
    ]
