# Generated by Django 5.2.6 on 2025-12-16 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_modality_abbreviature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prelationdocument',
            name='description',
        ),
        migrations.RemoveField(
            model_name='prelationdocument',
            name='file',
        ),
    ]
