# Generated by Django 5.2.6 on 2025-12-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_prelationdocument_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculararea',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='level',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modality',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prelationdocument',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prelationdocument',
            name='is_obligatory',
            field=models.BooleanField(default=True),
        ),
    ]
