# Generated by Django 5.2.6 on 2025-12-16 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_curriculararea_is_active_level_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrelationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('logic_type', models.CharField(choices=[('AND', 'Y'), ('OR', 'O')], default='AND', max_length=3)),
                ('group', models.IntegerField(default=1)),
                ('is_obligatory', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('prelation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='api.prelation')),
            ],
        ),
        migrations.DeleteModel(
            name='PrelationDocument',
        ),
    ]
