# Generated by Django 5.2.6 on 2025-12-16 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_prelationrequirement_delete_prelationdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prelationrequirement',
            name='is_obligatory',
        ),
    ]
