# Generated by Django 5.2.6 on 2025-12-30 05:35

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_prelationrequirement_is_obligatory'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.person')),
                ('role', models.ForeignKey(blank=True, help_text='Rol del usuario (grupo)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='api.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'api_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EvaluatorProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='evaluator_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curricular_areas', models.ManyToManyField(help_text='Áreas curriculares asignadas al evaluador', related_name='evaluators', to='api.curriculararea')),
                ('levels', models.ManyToManyField(help_text='Niveles asignados al evaluador', related_name='evaluators', to='api.level')),
                ('modalities', models.ManyToManyField(help_text='Modalidades asignadas al evaluador', related_name='evaluators', to='api.modality')),
            ],
            options={
                'verbose_name': 'Perfil de Evaluador',
                'verbose_name_plural': 'Perfiles de Evaluadores',
                'db_table': 'api_evaluator_profile',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teacher_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curricular_area', models.ForeignKey(help_text='Área curricular asignada al docente', on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='api.curriculararea')),
                ('level', models.ForeignKey(help_text='Nivel asignado al docente', on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='api.level')),
                ('modality', models.ForeignKey(help_text='Modalidad asignada al docente', on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='api.modality')),
            ],
            options={
                'verbose_name': 'Perfil de Docente',
                'verbose_name_plural': 'Perfiles de Docentes',
                'db_table': 'api_teacher_profile',
            },
        ),
        migrations.DeleteModel(
            name='PersonDocument',
        ),
    ]
