# Generated by Django 5.2.6 on 2025-12-30 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_user_evaluatorprofile_teacherprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('year', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fase',
                'verbose_name_plural': 'Fases',
                'db_table': 'api_phase',
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhaseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_datetime', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('curricular_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.curriculararea')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.level')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.modality')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.phase')),
            ],
            options={
                'verbose_name': 'Adjudicación de Fase',
                'verbose_name_plural': 'Adjudicaciones de Fases',
                'db_table': 'api_phase_assignment',
                'ordering': ['assignment_datetime'],
            },
        ),
        migrations.CreateModel(
            name='PhaseStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(choices=[('PUBLICATION', 'Publicación de las vacantes'), ('ACCREDITATION', 'Presentación de acreditación de requisitos'), ('TIE_EVALUATION', 'Evaluación de expedientes en caso de empate'), ('PRELIMINARY_RESULTS', 'Publicación de resultados preliminares'), ('CLAIMS', 'Presentación de reclamos'), ('CLAIM_RESOLUTION', 'Absolución de reclamos'), ('FINAL_RESULTS', 'Publicación de cuadro de mérito final')], max_length=30)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='api.phase')),
            ],
            options={
                'verbose_name': 'Etapa de Fase',
                'verbose_name_plural': 'Etapas de Fases',
                'db_table': 'api_phase_stage',
                'ordering': ['start_date'],
                'unique_together': {('phase', 'stage_type')},
            },
        ),
    ]
