# Generated by Django 5.2.6 on 2025-12-30 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_phase_phaseassignment_phasestage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vacante', 'verbose_name_plural': 'Vacantes'},
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='workday',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='api.phase'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='curricular_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.curriculararea'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='position',
            field=models.CharField(choices=[('DOCENTE', 'Docente'), ('AUXILIAR', 'Auxiliar de Educación')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='vacancy_reason',
            field=models.CharField(choices=[('LICENCIA', 'Licencia'), ('DESTAQUE', 'Destaque'), ('ENCARGATURA', 'Encargatura'), ('NUEVA_PLAZA', 'Nueva Plaza'), ('REASIGNACION', 'Reasignación'), ('OTRO', 'Otro')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='vacancy_type',
            field=models.CharField(choices=[('ORGANICA', 'Orgánica'), ('EVENTUAL', 'Eventual')], max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='vacancy',
            table='api_vacancy',
        ),
        migrations.CreateModel(
            name='EducationalInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.level')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.modality')),
            ],
            options={
                'verbose_name': 'Institución Educativa',
                'verbose_name_plural': 'Instituciones Educativas',
                'db_table': 'api_educational_institution',
                'ordering': ['name'],
                'unique_together': {('name', 'modality', 'level')},
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='educational_institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='api.educationalinstitution'),
        ),
    ]
