# Generated by Django 5.2.6 on 2025-12-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_vacancy_options_remove_vacancy_institution_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationalinstitution',
            options={'ordering': ['code'], 'verbose_name': 'Institución Educativa', 'verbose_name_plural': 'Instituciones Educativas'},
        ),
        migrations.AddField(
            model_name='educationalinstitution',
            name='code',
            field=models.CharField(blank=True, help_text='Código modular de la IE', max_length=20, null=True, unique=True),
        ),
    ]
